name: Project CI pipeline
run-name: ${{ github.actor }} is running the pipeline 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install requirements
        run: |
          make install
      - run: echo "💡 Virtual environment is ready with requirements installed."
      - name: Download data
        run: |
          make data
      - run: echo "💡 Data have been downloaded."
      - name: Train deep learning model
        run: |
          make model1
      - run: echo "💡 Model is trained."