[Classifier]
feat_dim = 256
kernel_size = 5
n_classes = 6

[make_labelled_dataset]
batch_size = 8
buffer_size = 5_000
seed = 123

[data]
n_validation_subjects = 5
seed = 123

[data.train]
feat_folder = 'data/UCI HAR Dataset/train/Inertial Signals'
labels_file = 'data/UCI HAR Dataset/train/y_train.txt'
subjects_file = 'data/UCI HAR Dataset/train/subject_train.txt'

[data.test]
feat_folder = 'data/UCI HAR Dataset/test/Inertial Signals'
labels_file = 'data/UCI HAR Dataset/test/y_test.txt'
subjects_file = 'data/UCI HAR Dataset/test/subject_test.txt'

[artefacts]
deep_learning_model = 'keras_artefacts'

[training]
max_epochs = 1
patience = 5
