[Classifier]
feat_dim = 128
kernel_size = 5
n_classes = 6

[make_labelled_dataset]
batch_size = 8
buffer_size = 5_000

[data]
train_feat_folder = 'data/UCI HAR Dataset/train/Inertial Signals'
train_labels_file = 'data/UCI HAR Dataset/train/y_train.txt'
train_subjects_file = 'data/UCI HAR Dataset/train/subject_train.txt'
test_feat_folder = 'data/UCI HAR Dataset/test/Inertial Signals'
test_labels_file = 'data/UCI HAR Dataset/test/y_test.txt'
test_subjects_file = 'data/UCI HAR Dataset/test/subject_test.txt'
n_validation_subjects = 5
