[Classifier]
n_feat = 9
feat_block_size = 3
encoder_dim = 64
dense_dim = 32
small_kernel_size = 5
large_kernel_size = 50
n_classes = 6

[data]

[data.train]
feat_folder = 'data/UCI HAR Dataset/train/Inertial Signals'
labels_file = 'data/UCI HAR Dataset/train/y_train.txt'
subjects_file = 'data/UCI HAR Dataset/train/subject_train.txt'
seed = 123
buffer_size = 7_352
n_validation_subjects = 5
batch_size = 8

[data.test]
feat_folder = 'data/UCI HAR Dataset/test/Inertial Signals'
labels_file = 'data/UCI HAR Dataset/test/y_test.txt'
subjects_file = 'data/UCI HAR Dataset/test/subject_test.txt'
labels_desc_file = 'data/UCI HAR Dataset/activity_labels.txt'
batch_size = 8

[artefacts]
model = 'model1'

[training]
max_epochs = 50
patience = 2
loss = "sparse_categorical_crossentropy"
metric = "sparse_categorical_accuracy"
