name: Project CI pipeline
run-name: ${{ github.actor }} is running the pipeline 🚀
on: [pull_request]
permissions:
  contents: read
  metadata: read
  packages: read
  pull-requests: write
jobs:
  Train-Deep-learning-model:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install requirements
        run: |
          make install
      - name: Download data
        run: |
          make data
      - name: Run tests
        run: |
          make test
      - name: Train deep learning model
        run: |
          make model1
      - name: Evaluate deep learning model
        id: evaluation
        run: |
          make eval-model1
      - name: Save results
        env:
          METRIC: ${{ steps.evaluation.outputs.stdout }}
        run: |
          echo $METRIC | grep "Model accuracy" | > report/model1.txt
      - name: Include results as a PR comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: report/model1.txt
          comment_tag: Model accuracy
