name: Project CI pipeline
run-name: ${{ github.actor }} is running the pipeline 🚀
on: [push]
jobs:
  Train-Deep-learning-model:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Install requirements
        run: |
          make install
      - run: echo "💡 Virtual environment is ready with requirements installed."
      - name: Download data
        run: |
          make data
      - run: echo "💡 Data have been downloaded."
      - name: Run tests
        run: |
          make test
      - run: echo "💡 All tests have run."
      - name: Train deep learning model
        run: |
          make model1
      - run: echo "💡 Model is trained."
      - name: Evaluate deep learning model
        id: evaluation
        run: |
          make eval-model1
      - name: Save results
        env:
          METRIC: ${{ steps.evaluation.outputs.stdout }}
        run: |
          echo $METRIC > report/model1.txt
      - run: echo "💡 Model results have been saved to a file."
      - name: Include results as a PR comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: report/model1.txt
          comment_tag: Model accuracy
